"""add_academic_and_calendar_tables

Revision ID: 1581a3c98b1e
Revises: 0b572e8d262c
Create Date: 2026-08-07 11:59:53.976922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1581a3c98b1e'
down_revision: Union[str, None] = '0b572e8d262c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'leave', name='attendance_status'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)

    op.create_table('calendar_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('exam', 'class', 'reminder', 'other', name='event_type'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_student_id'), ['student_id'], unique=False)

    op.create_table('daily_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('topics_to_teach', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_plans_student_id'), ['student_id'], unique=False)

    op.create_table('fee_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('paid', 'pending', name='fee_status'), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_records_student_id'), ['student_id'], unique=False)

    op.create_table('homework',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('assigned', 'completed', 'incomplete', name='homework_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homework_student_id'), ['student_id'], unique=False)

    op.create_table('syllabus',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('chapter', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'teaching', 'revision', 'completed', name='syllabus_status'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('syllabus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_syllabus_student_id'), ['student_id'], unique=False)

    op.create_table('tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('exam_name', sa.String(length=255), nullable=False),
    sa.Column('exam_type', sa.Enum('school', 'tuition', name='exam_type'), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('obtained_marks', sa.Float(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tests_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tests_student_id'))

    op.drop_table('tests')
    with op.batch_alter_table('syllabus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_syllabus_student_id'))

    op.drop_table('syllabus')
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homework_student_id'))

    op.drop_table('homework')
    with op.batch_alter_table('fee_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_records_student_id'))

    op.drop_table('fee_records')
    with op.batch_alter_table('daily_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_plans_student_id'))

    op.drop_table('daily_plans')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_student_id'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))

    op.drop_table('attendance')
    # ### end Alembic commands ###
